// dataService.ts

export const dataService = [
  {
    name: "Extensiones de pestañas clásicas",
    description: "Leer información en el icono (i)",
    duration: 90, // 1 hora 30 minutos en minutos
    price: 21000,
    category: "pestañas",
  },
  {
    name: "Extensiones de pestañas Efecto rimmel",
    description: "Leer información en el icono (i)",
    duration: 120, // 2 horas en minutos
    price: 27000,
    category: "pestañas",
  },
  {
    name: "Extensiones de pestañas Híbridas",
    description: "Leer información en el icono (i)",
    duration: 90,
    price: 21000,
    category: "pestañas",
  },
  {
    name: "Extensiones de pestañas inferiores",
    description: "Leer información en el icono (i)",
    duration: 30,
    price: 15000,
    category: "pestañas",
  },
  {
    name: "Extensiones de pestañas Volumen Full +4D",
    description: "Leer información en el icono (i)",
    duration: 120,
    price: 27000,
    category: "pestañas",
  },
  {
    name: "Extensiones de pestañas Volumen Tech",
    description: "Leer información en el icono (i)",
    duration: 90,
    price: 27000,
    category: "pestañas",
  },
  {
    name: "Lifting de pestañas + color y nutrición",
    description: "Leer información en el icono (i)",
    duration: 90,
    price: 27000,
    category: "pestañas",
  },
  {
    name: "Remoción de extensiones de otro lugar",
    description: "Leer información en el icono (i)",
    duration: 30,
    price: 12000,
    category: "pestañas",
  },
  {
    name: "Remoción de extensiones de TR",
    description: "Leer información en el icono (i)",
    duration: 30,
    price: 10000,
    category: "pestañas",
  },
  {
    name: "Cobertura de canas (cejas ó pestañas)",
    description: "Leer información en el icono (i)",
    duration: 30,
    price: 15000,
    category: "cejas",
  },
  {
    name: "Diseño de cejas + sombreado /relleno con henna",
    description: "Leer información en el icono (i)",
    duration: 90,
    price: 22000,
    category: "cejas",
  },
  {
    name: "Laminado de cejas con color",
    description: "Leer información en el icono (i)",
    duration: 60,
    price: 25000,
    category: "cejas",
  },
  {
    name: "Laminado de cejas sin color",
    description: "Leer información en el icono (i)",
    duration: 30,
    price: 20000,
    category: "cejas",
  },
  {
    name: "Perfilado de cejas",
    description: "Leer información en el icono (i)",
    duration: 30,
    price: 15000,
    category: "cejas",
  },
  {
    name: "Tintura de pestañas o cejas",
    description: "Leer información en el icono (i)",
    duration: 30,
    price: 12000,
    category: "otros",
  },
  {
    name: "Asesoría y orientación",
    description: "Leer información en el icono (i)",
    duration: 30,
    price: 10000,
    category: "asesoria",
  },
  {
    name: "Lifting de pestañas + laminado de cejas",
    description: "Profesional: 1 hora Cliente: 1 hora 30 minutos",
    duration: 90,
    price: 35000,
    category: "combos",
  },
  {
    name: "Perfilado de cejas + cobertura de canas",
    description: "Leer información en el icono (i)",
    duration: 30,
    price: 25000,
    category: "combos",
  },
];
